substrate:
  geometry:
    myocytes:
      data: # specify the myocyte Polyhedra here
        - Vertices:
          - [0.1, 0.1, 0.1]
          - [0.1, 0.9, 0.1]
          - [0.9, 0.1, 0.1]
          - [0.1, 0.1, 0.9]
          Faces:
          - [1, 2, 3]
          - [1, 2, 4]
          - [1, 3, 4]
          - [2, 3, 4]
        - Vertices:
          - [0.1, 1.1, 0.1]
          - [0.1, 1.9, 0.1]
          - [0.9, 1.1, 0.1]
          - [0.1, 1.1, 0.9]
          Faces:
          - [1, 2, 3]
          - [1, 2, 4]
          - [1, 3, 4]
          - [2, 3, 4]
    LxLyLz:
      - 1 # block.Lx
      - 2 # block.Ly
      - 1 # block.Lz
